### ISSUE TITLE
Fix the Google Forms results printouts

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/replicability-presentation2019#1]
The PDFs in text/ (Replication and You *.pdf) are broken - only the first page printed. To be fixed.

**Comment by dwasser** [comment]
@larsvilhuber  Sorry-just now getting to this. It is not clear to me how the pdfs are being produced. Can you give me a bit of guidance? Thanks.

**Comment by larsvilhuber** [comment]
The PDFs within text/ in this repo are generated from the Google Survey forms at https://drive.google.com/drive/u/0/folders/1wSuJGHO4ApZMo-4tKPL9XIlDB75CNa7u. As far as I can tell, the only way to generate a PDF of the results is to "print" them - to a PDF. However, when I tried, on Firefox, only the first page was printed. Please try and regenerate them, checking that the complete PDF is printed.

**Comment by larsvilhuber** [comment]
@dwasser Alternatively, there is a first stab at R code to generate similar graphs from the raw data. The PDF printing is a shortcut, for now.
